#!/usr/bin/env sh

Copyright © 2015-2021 the original authors.

Licensed under the Apache License, Version 2.0 (the "License");

you may not use this file except in compliance with the License.

You may obtain a copy of the License at

https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software

distributed under the License is distributed on an "AS IS" BASIS,

WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and

limitations under the License.

##############################################################################

Gradle start up script for POSIX generated by Gradle

https://github.com/gradle/gradle/blob/HEAD/src/packaging/src/unix/gradlew

##############################################################################

Attempt to set APP_HOME

Resolve links: $0 may be a link

PRG="$0"
while [ -h "$PRG" ] ; do
ls=ls -ld "$PRG"
link=expr "$ls" : '.*-> \(.*\)$'
if expr "$link" : '/.*' > /dev/null; then
PRG="$link"
else
PRG=dirname "$PRG"/"$link"
fi
done

SAVED="pwd"
cd "dirname \"$PRG\"" >/dev/null
APP_HOME="pwd -P"
cd "$SAVED"

APP_NAME="Gradle"
APP_BASE_NAME=basename "$0"

Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

Use the maximum available, or set MAX_FD to a smaller value

if [ -n "$MAX_FD" ] ; then
DESCRIPTOR_LIMIT=ulimit -n 2>/dev/null
if [ $? -eq 0 ] ; then
if [ "$DESCRIPTOR_LIMIT" = "unlimited" ] ; then
MAX_FD=$DESCRIPTOR_LIMIT
else
MAX_FD=expr $DESCRIPTOR_LIMIT / 2
fi
ulimit -n "$MAX_FD" 2>/dev/null
fi
fi

For Cygwin, ensure paths are in UNIX format before anything is touched

if $cygwin ; then
[ -n "$JAVA_HOME" ] && JAVA_HOME=cygpath --unix "$JAVA_HOME"
fi

Determine the Java command to use to start the JVM.

if [ -n "$JAVA_HOME" ] ; then
if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
# IBM's JDK on AIX uses strange locations for the java executable
JAVACMD="$JAVA_HOME/jre/sh/java"
else
JAVACMD="$JAVA_HOME/bin/java"
fi
if [ ! -x "$JAVACMD" ] ; then
die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi
else
JAVACMD="java"
which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."

fi

Increase the maximum file descriptor limit if possible

if [ "$cygwin" = "false" ] && [ "$darwin" = "false" ] && [ "$nonstop" = "false" ] ; then
MAX_FD_LIMIT=ulimit -H -n 2>/dev/null
if [ $? -eq 0 ] ; then
if [ -n "$MAX_FD" ] ; then
if [ "$MAX_FD" -gt "$MAX_FD_LIMIT" ] ; then
MAX_FD="$MAX_FD_LIMIT"
fi
ulimit -n "$MAX_FD" 2>/dev/null
fi
fi
fi

Split up CLASSPATH and JVM_OPTS in case they contain spaces

shellcheck disable=SC2206

shellcheck disable=SC2086

exec "$JAVACMD" "$@"
